# Run on a schedule
trigger: none
pr: none

schedules:
  - cron: '0 9 * * Mon-Thu'
    displayName: Nightly Release Schedule
    always: true
    branches:
      include:
        - main

resources:
  repositories:
    - repository: templates
      type: github
      name: microsoft/vscode-engineering
      ref: main
      endpoint: Monaco

parameters:
    - name: publishExtension
      displayName: 🚀 Publish Pre-Release
      type: boolean
      default: false

extends:
  template: azure-pipelines/extension/pre-release.yml@templates
  parameters:
    credscanSuppressionsFile: $(Build.SourcesDirectory)/CredScanSuppressions.json
    standardizedVersioning: true
    l10nSourcePaths: ./src
    customNPMRegistry: ''
    publishExtension: ${{ parameters.publishExtension }}
    buildSteps:
      - script: npm ci
        displayName: Install dependencies

      - script: npm run package
        displayName: Compile
