trigger:
  batch: true
  branches:
    include:
      - main
  tags:
    include: ['*']
pr: none

resources:
  repositories:
    - repository: templates
      type: github
      name: microsoft/vscode-engineering
      ref: main
      endpoint: Monaco

parameters:
    - name: publishExtension
      displayName: 🚀 Publish Stable
      type: boolean
      default: false

extends:
  template: azure-pipelines/extension/stable.yml@templates
  parameters:
    credscanSuppressionsFile: $(Build.SourcesDirectory)/CredScanSuppressions.json
    l10nSourcePaths: ./src
    customNPMRegistry: ''
    publishExtension: ${{ parameters.publishExtension }}
    buildSteps:
      - script: npm ci
        displayName: Install dependencies

      - script: npm run package
        displayName: Compile
